name: Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - uses: actions/setup-node@v1
      name: Setup Node
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Test
      run: cargo test
